"""update fk actions

Revision ID: aa08c3c3838e
Revises: 2af320dc278f
Create Date: 2024-01-25 21:16:07.307469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa08c3c3838e'
down_revision = '2af320dc278f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('bookings_restaurant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bookings_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint('restaurants_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reviews_restaurant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_restaurant_id_fkey', 'restaurants', ['restaurant_id'], ['id'])
        batch_op.create_foreign_key('reviews_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('restaurants_owner_id_fkey', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bookings_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('bookings_restaurant_id_fkey', 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###
